apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ridely-api-monitor
  namespace: ridely
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ridely-api
  namespaceSelector:
    matchNames:
      - ridely
  endpoints:
    - port: http # name of port in Service
      path: /metrics
      interval: 15s
