apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridely-api
  namespace: ridely
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ridely-api
  template:
    metadata:
      labels:
        app: ridely-api
    spec:
      containers:
        - name: app
          image: joemartin2001/ridely-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: ridely-app-config
            - secretRef:
                name: ridely-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ridely-api
  namespace: ridely
spec:
  selector:
    app: ridely-api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
  type: NodePort # For local dev; use LoadBalancer/Ingress in cloud
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ridely-api-monitor
  namespace: ridely
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ridely-api
  namespaceSelector:
    matchNames:
      - ridely
  endpoints:
    - port: http # name of port in Service
      path: /metrics
      interval: 15s
