apiVersion: v1
kind: ConfigMap
metadata:
  name: ridely-app-config
  namespace: ridely
data:
  NODE_ENV: 'production' # or whatever you use
  PORT: '4000' # match your ${PORT}
  FRONTEND_URL: 'http://localhost:3000' # adjust

  DB_HOST: 'postgres' # <- postgres service name
  DB_PORT: '5432'
  DB_SSL: 'false' # match your compose

  S3_BUCKET: 'ridely' # your ${S3_BUCKET}
  S3_ENDPOINT: 'http://minio:9000' # internal service URL
  S3_PUBLIC_ENDPOINT: 'http://localhost:9000' # adjust for ingress
  S3_REGION: 'us-east-1'
  S3_FORCE_PATH_STYLE: 'true'

  FALLBACK_LANGUAGE: 'en'
  S3_PUBLIC_BASE_URL: 'http://localhost:9000/ridely'
  SUPABASE_URL: 'https://dbunxvmwjytgxdnslymd.supabase.co'
  OTP_PROVIDER: 'email'
