apiVersion: v1
kind: ConfigMap
metadata:
  name: ridely-config
data:
  NODE_ENV: 'production'
  PORT: '4000'
  FRONTEND_URL: 'http://localhost:3000'
  DB_HOST: 'postgres'
  DB_PORT: '5432'
  DB_NAME: 'ridely'
  S3_BUCKET: 'ridely'
  S3_ENDPOINT: 'http://minio:9000'
  S3_PUBLIC_ENDPOINT: 'http://localhost:9000'
  S3_REGION: 'us-east-1'
  S3_FORCE_PATH_STYLE: 'true'
