apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ridely-ingress
spec:
  rules:
    - host: ridely.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ridely-api
                port:
                  number: 4000
