apiVersion: v1
kind: Secret
metadata:
  name: ridely-secrets
type: Opaque
stringData:
  JWT_SECRET: '9fab5279-b888-4c8c-8fc6-ce5523a02cf3'
  DB_USER: 'postgres'
  DB_PASSWORD: 'postgres'
  S3_KEY: 'minio'
  S3_SECRET: 'minio12345'
  MINIO_ROOT_USER: 'minio'
  MINIO_ROOT_PASSWORD: 'minio12345'
